// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function Chat(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function CompleteTask(arg1:string,arg2:any):Promise<void>;

export function CreateGoal(arg1:models.Goal):Promise<models.Goal>;

export function CreateTask(arg1:models.Task):Promise<models.Task>;

export function DeleteGoal(arg1:string):Promise<void>;

export function GetConversationHistory(arg1:string,arg2:number):Promise<Array<models.Conversation>>;

export function GetGoal(arg1:string):Promise<models.Goal>;

export function GetTask(arg1:string):Promise<models.Task>;

export function GetTasksByGoalID(arg1:string):Promise<Array<models.Task>>;

export function GetTodaysTasks():Promise<Array<models.Task>>;

export function LogStruggle(arg1:string,arg2:string):Promise<void>;

export function UpdateGoal(arg1:models.Goal):Promise<void>;
