// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function CompleteTask(arg1, arg2) {
  return window['go']['main']['App']['CompleteTask'](arg1, arg2);
}

export function CreateGoal(arg1) {
  return window['go']['main']['App']['CreateGoal'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteLLMProviderConfig(arg1) {
  return window['go']['main']['App']['DeleteLLMProviderConfig'](arg1);
}

export function GetConversationHistory(arg1, arg2) {
  return window['go']['main']['App']['GetConversationHistory'](arg1, arg2);
}

export function GetGoal(arg1) {
  return window['go']['main']['App']['GetGoal'](arg1);
}

export function GetLLMProviderConfigs() {
  return window['go']['main']['App']['GetLLMProviderConfigs']();
}

export function GetLLMProviders() {
  return window['go']['main']['App']['GetLLMProviders']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTasksByGoalID(arg1) {
  return window['go']['main']['App']['GetTasksByGoalID'](arg1);
}

export function GetTodaysTasks() {
  return window['go']['main']['App']['GetTodaysTasks']();
}

export function LogStruggle(arg1, arg2) {
  return window['go']['main']['App']['LogStruggle'](arg1, arg2);
}

export function SaveLLMProviderConfig(arg1) {
  return window['go']['main']['App']['SaveLLMProviderConfig'](arg1);
}

export function UpdateGoal(arg1) {
  return window['go']['main']['App']['UpdateGoal'](arg1);
}

export function UpdateLLMProviderConfig(arg1) {
  return window['go']['main']['App']['UpdateLLMProviderConfig'](arg1);
}
